version: '3.8'

services:

  ## MySQL Docker Compose Config application
  mysqlapplication:
    container_name: mysqlapplication
    image: mysql:5.7
    hostname: mysqlapplication
    environment:
      - MYSQL_ROOT_PASSWORD=sofrecom
      - MYSQL_DATABASE=application-service
    volumes:
      - ./mysql-application-data:/var/lib/mysql-application
      - ./gestionapps.sql:/docker-entrypoint-initdb.d/gestionapps.sql
    expose:
      - "3309"
    ports:
      - "3309:3306"
    restart: always

  ## MySQL Docker Compose Config talent
  mysql-talent:
    container_name: mysql-talent
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=sofrecom
      - MYSQL_DATABASE=talent-service
    volumes:
      - ./mysql-talent-data:/var/lib/mysql-talent
      - ./gestiontalents.sql:/docker-entrypoint-initdb.d/gestiontalents.sql
    expose:
      - "3307"
    ports:
      - "3307:3306"
    restart: always

  ## MySQL Docker Compose Config notification
  mysql-notification:
    container_name: mysql-notification
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=sofrecom
      - MYSQL_DATABASE=notification-service
    volumes:
      - ./mysql-notification-data:/var/lib/mysql-notification
      - ./gestionnotifications.sql:/docker-entrypoint-initdb.d/gestionnotifications.sql
    expose:
      - "3308"
    ports:
      - "3308:3306"
    restart: always

  ## Keycloak Config with Mysql database
  keycloak-mysql:
    container_name: keycloak-mysql
    image: mysql:5.7
    volumes:
      - ./mysql-keycloak-data:/var/lib/mysql-keycloak
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  ## api-gateway Config
  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8181/realms/SofManagers
      - eureka.client.serviceUrl.defaultZone=http://eureka:sofrecom@discovery-server:8761/eureka
    depends_on:
      - discovery-server
      - keycloak

  ## discovery-server Config
  discovery-server:
    container_name: discovery-server
    build:
      context: ./discovery-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  ## gestion-app Config
  gestion-application:
    container_name: gestion-application
    build:
      context: ./gestion-application
      dockerfile: Dockerfile
    environment:
      - spring.datasource.url=jdbc:mysql://mysqlapplication:3309/application-service?useSSL=false
      - spring.datasource.username=root
      - spring.datasource.password=sofrecom
      - eureka.client.serviceUrl.defaultZone=http://eureka:sofrecom@discovery-server:8761/eureka
    depends_on:
      - discovery-server
      - api-gateway
      - mysqlapplication

  ## gestion-talent Config
  gestion-talent:
    container_name: gestion-talent
    build:
      context: ./gestion-talent
      dockerfile: Dockerfile
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka:sofrecom@discovery-server:8761/eureka
      - spring.datasource.url=jdbc:mysql://mysql-talent:3307/talent-service?useSSL=false
      - spring.datasource.username=root
      - spring.datasource.password=sofrecom
    depends_on:
      - discovery-server
      - api-gateway
      - mysql-talent

  ## gestion-notif Config
  gestion-usernotifications:
    container_name: gestion-usernotifications
    build:
      context: ./authUserAndNotifications
      dockerfile: Dockerfile
    environment:
      - spring.datasource.url=jdbc:mysql://mysql-notification:3306/notification-service?useSSL=false
      - spring.datasource.username=root
      - spring.datasource.password=sofrecom
      - eureka.client.serviceUrl.defaultZone=http://eureka:sofrecom@discovery-server:8761/eureka
      - keycloak.auth-server-url=http://keycloak:8181
      - keycloak.realm=SofManagers
      - keycloak.client-id=front-client
      - keycloak.admin.username=admin
      - keycloak.admin.password=admin
    depends_on:
      - discovery-server
      - api-gateway
      - keycloak
      - mysql-notification

  ## keycloak Config
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.1.1
    command: [ "start-dev", "--import-realm" ]
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    expose:
      - 8181
    ports:
      - "8181:8080"
    volumes:
      - ./realms/:/opt/keycloak/data/import/
    depends_on:
      - keycloak-mysql

  ## front-app Config
  front-app:
    container_name: front-app
    build:
      context: ./front-application
      dockerfile: Dockerfile
    environment:
      - NPM_CONFIG_STRICT_SSL=false
    depends_on:
      - api-gateway
      - keycloak


